# Generated by Django 4.0.2 on 2022-02-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_list_date_alter_listing_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photos_%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photos_%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='photos_%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='photos_%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos_%Y-%m-%d'),
        ),
    ]
